name: Yehan Git Sync Action
author: Ye Han <zhangtong.mr@aliyun.com>
description: Sync current repo to specified repo
branding:
  icon: upload-cloud
  color: blue
inputs:
  source_repo_url:
    description: source gitHub repo url
    required: true
  source_branch:
    description: branch name to sync from
    required: true
  destination_repo_url:
    description: destination repo url
    required: true
  destination_branch:
    description: branch name to sync to
    required: true
  ssh_private_key:
    description: SSH key used to authenticate with git clone urls provided (optional if public or https clone url with authentication)
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
  args:
    - ${{ inputs.source_repo_url }}
    - ${{ inputs.source_branch }}
    - ${{ inputs.destination_repo_url }}
    - ${{ inputs.destination_branch }}